[[plugins]]
  package = "@netlify/plugin-lighthouse"


  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "contact"

  [[plugins.inputs.audits]]
    path = "something-that-doesnt-exist.html"

  [[plugins.inputs.audits]]
    path = "about/index.html"




