[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugin.inputs]
    fail_deploy_on_score_thresholds = "true"

  [plugin.inputs.thresholds]
    seo = "1"


  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "contact.html"

  [[plugins.inputs.audits]]
    serveDir = "about"
    output_path = "reports/about.html"




